### ISSUE TITLE
Compile error when switch branch

### ISSUE THREAD

**Issue by ultwcz** [NVIDIA/edk2-nvidia#63]
Hi, now when i switch branch main to r35.3.1-updates, it compiled failed
> ERROR - Invalid file path: ('DynamicTablesPkg/Library/Acpi/Arm/AcpiSlitLibArm/AcpiSlitLibArm.inf',)

> ERROR - Build.py #000 from /home/ultwcz/work/prj/nx/nvidia-uefi-test/edk2-nvidia/Platform/NVIDIA/Jetson/Jetson.dsc(941): File/directory not found in workspace

What should i do?

Thank you.

**Comment by jgarver** [comment]
Hi, @ultwcz!

You'll also need to switch branches in the supporting repos (edk2, edk2-platforms, etc.).  There's also new repos you'll need that have been added since r35.3.1-updates.  Doing this manually will be error-prone.  It's better to rely on the edkrepo tool and our configured combinations.

I recommend using "edkrepo checkout main" to migrate an existing workspace to the main combo.  Or simply create a new workspace.

**Comment by ultwcz** [comment]
OK, i used the command `edk2_docker edkrepo clone nvidia-uefi NVIDIA-Platforms r35.3.1-updates`  and it was ok.
Thank you.

**Comment by jgarver** [comment]
Great!  Closing this issue then.
